spring.application.name=day30-capstone
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

management.endpoints.web.exposure.include=health,info
info.app.name=Día 30 - Task Manager API (Capstone)
info.app.autor=Lucas Kraglievich

jwt.secret=miclaveultrasecretaparaeljwtdeldiaTreintaCapstone2026
jwt.expiration=3600000
