spring.datasource.url=jdbc:postgresql://localhost:5432/tareas_db
spring.datasource.username=postgres
spring.datasource.password=Lucaskra09
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true